apiVersion: v1
kind: Template
metadata:
  name: bridge-template
  annotations:
    description: "Installation of the Birdge Database"
    tags: "bridge"
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: bridge-db-pvc
    labels:
      app: bridge-db
  spec:
    storageClassName: bridge-db
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 8Gi
      limits:
        storage: 24Gi
        
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: postgres-config
    labels:
      app: bridge-db
  data:
    POSTGRES_DB: ****
    POSTGRES_USER: ****
    POSTGRES_PASSWORD: **** 
    ENVIRONMENT: PROD
    PGDATA: "/var/lib/postgresql/data/db-files"

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: bridge-db
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: bridge-db
    template:
      metadata:
        labels: 
          app: bridge-db
      spec:
        imagePullSecrets:
          - name: sbs-registry
        containers:
          - name: bridge-db
            imagePullPolicy: Always
            image: sensiblebuildingscience/bridge-db-v3
            envFrom:
              - configMapRef: 
                  name: postgres-config
            ports:
              - containerPort: 5432
            volumeMounts:
              - name: bridge-db-volume 
                mountPath:  "/var/lib/postgresql/data" 
            resources: 
              limits:
                cpu: 500m
        volumes:
          - name: bridge-db-volume
            persistentVolumeClaim:
              claimName: bridge-db-pvc

- apiVersion: v1
  kind: Service
  metadata:
    name:  bridge-db-service
    labels:
      app: bridge-db
  spec:
    selector:
      app:  bridge-db
    type: NodePort
    ports:
      - port: 15432
        targetPort: 5432
